"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

-------------------------

Runtime : 94 ms , Memory : 14  MB
@author : sham-marol

"""

class Solution:
    def findTheDifference(self, sstr: str, tstr: str) -> str:
        
        slist = list(sstr)
        tlist = list(tstr)
        
        for t in tlist.copy():
            if t in slist:
                tlist.remove(t)
                slist.remove(t)
            #print("%s | %s | %s " % (t,tlist,slist))
        return "".join(tlist)
                
